language: R
sudo: required
cache:
 - packages
 - apt: true

r_github_packages:
  - r-lib/covr
  - r-lib/pkgdown

matrix:
  include:
  - r: release
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
    after_success:
      - Rscript -e 'covr::codecov()'
      - rm -rf RTest.Rcheck
      - Rscript -e 'devtools::document()'
      - Rscript -e 'pkgdown::build_site()'
    deploy:
      - provider: pages
        skip-cleanup: true
        github-token: $TRAVIS_DEPLOY_KEY_ORG
        keep-history: false
        local-dir: docs
        on:
          tags: true
        target_branch: gh-pages
  - r: release
    os: osx
    osx_image: xcode10.1
    compiler:
      - clang
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
