test_that("lipid name validation works", {
  expect_equal(rgoslin::isValidLipidName("PC(32:0)"), TRUE)
})

test_that("lipid name parsing works", {
  originalName <- "LPC(34:2;1)"
  df <- rgoslin::parseLipidName(originalName)
  expect_equal(is.data.frame(df), TRUE)
  expect_equal(df[["Original.Name"]], originalName)
  expect_equal(df[["Normalized.Name"]], "LPC 34:2;O")
  expect_equal(df[["Lipid.Maps.Category"]], "GP")
})

test_that("lipid name parsing with grammar works", {
  originalName <- "LPC(34:1)"
  df <- rgoslin::parseLipidNameWithGrammar(originalName, "SwissLipids")
  expect_equal(is.data.frame(df), TRUE)
  expect_equal(df[["Original.Name"]], originalName)
  expect_equal(df[["Normalized.Name"]], "LPC 34:1")
  expect_equal(df[["Species.Name"]], "LPC 34:1")
  expect_equal(df[["Molecular.Species.Name"]], "NA")
  expect_equal(df[["Sn.Position.Name"]], "NA")
  expect_equal(df[["Structure.Defined.Name"]], "NA")
  expect_equal(df[["Full.Structure.Name"]], "NA")
  expect_equal(df[["Lipid.Maps.Category"]], "GP")
  
  originalName <- "TG(16:1(5E)/18:0/20:2(3Z,6Z))"
  df <- rgoslin::parseLipidNameWithGrammar(originalName, "LipidMaps")
  expect_equal(is.data.frame(df), TRUE)
  expect_equal(df[["Original.Name"]], originalName)
  expect_equal(df[["Normalized.Name"]], "TG 16:1(5E)/18:0/20:2(3Z,6Z)")
  expect_equal(df[["Species.Name"]], "TG 54:3")
  expect_equal(df[["Molecular.Species.Name"]], "TG 16:1_18:0_20:2")
  expect_equal(df[["Sn.Position.Name"]], "TG 16:1/18:0/20:2")
  expect_equal(df[["Structure.Defined.Name"]], "TG 16:1(5)/18:0/20:2(3,6)")
  expect_equal(df[["Full.Structure.Name"]], "TG 16:1(5E)/18:0/20:2(3Z,6Z)")
  expect_equal(df[["Lipid.Maps.Category"]], "GL")
  expect_equal(df[["FA1.DB.Positions"]], "[5E]")
  expect_equal(df[["FA2.DB.Positions"]], "[]")
  expect_equal(df[["FA3.DB.Positions"]], "[3Z, 6Z]")
})

test_that("multiple lipid names parsing works", {
  originalNames <- c("PC(32:0)", "LPC(34:2;1)", "TG(18:1_18:0_16:1)", "TAG 16:1/18:0/20:2")
  df <- rgoslin::parseLipidNames(originalNames)
  expect_equal(is.data.frame(df), TRUE)
  expect_equal(nrow(df), 4)
  expect_equal(as.character(df[1, "Original.Name"]), originalNames[[1]])
  expect_equal(as.character(df[2, "Original.Name"]), originalNames[[2]])
  expect_equal(as.character(df[3, "Original.Name"]), originalNames[[3]])
  expect_equal(as.character(df[4, "Original.Name"]), originalNames[[4]])
  expect_equal(as.character(df[1, "Normalized.Name"]), "PC 32:0")
  expect_equal(as.character(df[2, "Normalized.Name"]), "LPC 34:2;O")
  expect_equal(as.character(df[3, "Normalized.Name"]), "TG 18:1_18:0_16:1")
  expect_equal(as.character(df[4, "Normalized.Name"]), "TG 16:1/18:0/20:2")
})

test_that("multiple lipid names parsing with grammar works", {
  originalNames <- c("PC 32:1","LPC 34:1","TAG 18:1_18:0_16:1")
  df <- rgoslin::parseLipidNamesWithGrammar(originalNames, "Goslin")
  expect_equal(is.data.frame(df), TRUE)
  expect_equal(nrow(df), 3)
  expect_equal(as.character(df[1, "Original.Name"]), originalNames[[1]])
  expect_equal(as.character(df[2, "Original.Name"]), originalNames[[2]])
  expect_equal(as.character(df[3, "Original.Name"]), originalNames[[3]])
  expect_equal(as.character(df[1, "Normalized.Name"]), "PC 32:1")
  expect_equal(as.character(df[2, "Normalized.Name"]), "LPC 34:1")
  expect_equal(as.character(df[3, "Normalized.Name"]), "TG 18:1_18:0_16:1")
})

test_that("lipid name with adduct parsing with grammar works", {
  originalName <- "PC 34:1 [M+H]1+"
  df <- rgoslin::parseLipidNameWithGrammar(originalName, "Goslin")
  expect_equal(is.data.frame(df), TRUE)
  expect_equal(df[["Original.Name"]], originalName)
  expect_equal(df[["Normalized.Name"]], "PC 34:1")
  expect_equal(df[["Adduct"]], "[M+H]1+")
  expect_equal(df[["Adduct.Charge"]], 1)
  expect_equal(df[["Mass"]], 1)
  expect_equal(df[["Species.Name"]], "PC 34:1")
  expect_equal(df[["Molecular.Subspecies.Name"]], "NA")
  expect_equal(df[["Structural.Subspecies.Name"]], "NA")
  expect_equal(df[["Isomeric.Subspecies.Name"]], "NA")
  expect_equal(df[["Lipid.Maps.Category"]], "GP")
})
